# Generated by Django 5.0.1 on 2025-02-04 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_email_donorregister_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='staf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.stafreg'),
            preserve_default=False,
        ),
    ]
