# Generated by Django 5.0.1 on 2025-02-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_child_staf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='child',
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='child',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='child',
        ),
        migrations.DeleteModel(
            name='DailyActivity',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
