# Generated by Django 5.0.1 on 2025-02-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contactmessage_remove_dailyactivity_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField()),
                ('phone', models.IntegerField()),
                ('password', models.TextField()),
            ],
        ),
    ]
