# Generated by Django 5.1.6 on 2025-03-22 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_adminreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('children', models.ManyToManyField(related_name='events', to='app.child')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stafreg')),
            ],
        ),
    ]
