# Generated by Django 5.1.6 on 2025-03-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
